In [2]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('../DATA/bank_note_data.txt',delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
data.shape

(1372, 5)

In [6]:
labels = data[:,4]

In [7]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [8]:
features = data[:,0:4]

In [9]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [19]:
X = features
y = labels

# 데이터 준비

In [17]:
from sklearn.model_selection import train_test_split

In [20]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [23]:
from sklearn.preprocessing import MinMaxScaler

In [24]:
scaler_object = MinMaxScaler()

In [25]:
scaler_object.fit(X_train)

MinMaxScaler()

In [26]:
scaled_X_train = scaler_object.transform(X_train)

In [27]:
scaled_X_test = scaler_object.transform(X_test)

In [28]:
 scaled_X_train.max()

1.0000000000000002

# 모델 설계

In [31]:
from keras.models import Sequential
from keras.layers import Dense

In [32]:

model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

model.add(Dense(8,activation='relu'))

# sigmoid가 아웃풋이 0 아니면 1이 나온다
model.add(Dense(1,activation='sigmoid'))

2022-10-08 11:33:18.584237: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.


# 모델 훈련

In [33]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [34]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
29/29 - 1s - loss: 0.6625 - accuracy: 0.5680 - 701ms/epoch - 24ms/step
Epoch 2/50
29/29 - 0s - loss: 0.6555 - accuracy: 0.5800 - 32ms/epoch - 1ms/step
Epoch 3/50
29/29 - 0s - loss: 0.6500 - accuracy: 0.5822 - 33ms/epoch - 1ms/step
Epoch 4/50
29/29 - 0s - loss: 0.6440 - accuracy: 0.5843 - 33ms/epoch - 1ms/step
Epoch 5/50
29/29 - 0s - loss: 0.6374 - accuracy: 0.5952 - 31ms/epoch - 1ms/step
Epoch 6/50
29/29 - 0s - loss: 0.6270 - accuracy: 0.6192 - 29ms/epoch - 1ms/step
Epoch 7/50
29/29 - 0s - loss: 0.6060 - accuracy: 0.6594 - 36ms/epoch - 1ms/step
Epoch 8/50
29/29 - 0s - loss: 0.5774 - accuracy: 0.6801 - 30ms/epoch - 1ms/step
Epoch 9/50
29/29 - 0s - loss: 0.5445 - accuracy: 0.7301 - 31ms/epoch - 1ms/step
Epoch 10/50
29/29 - 0s - loss: 0.5177 - accuracy: 0.7443 - 30ms/epoch - 1ms/step
Epoch 11/50
29/29 - 0s - loss: 0.4959 - accuracy: 0.7519 - 31ms/epoch - 1ms/step
Epoch 12/50
29/29 - 0s - loss: 0.4775 - accuracy: 0.7617 - 29ms/epoch - 1ms/step
Epoch 13/50
29/29 - 0s - loss: 0.46

In [49]:
# predict_classes는 2.6 이후부터 없음.
# (model.predict(scaled_X_test) > 0.5).astype("int32")

In [40]:
model.metrics_names

['loss', 'accuracy']

# 훈련 모델 평가

In [41]:
from sklearn.metrics import confusion_matrix,classification_report

In [42]:
predictions = (model.predict(scaled_X_test) > 0.5).astype("int32")

15/15 [==============================] - 0s 1ms/step


In [43]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  9, 187]])

In [44]:
print(classification_report(y_test,predictions))

              precision    recall  f1-score   support

         0.0       0.97      0.99      0.98       257
         1.0       0.98      0.95      0.97       196

    accuracy                           0.97       453
   macro avg       0.97      0.97      0.97       453
weighted avg       0.97      0.97      0.97       453



In [45]:
model.save('keras_basics.h5')

In [46]:
from keras.models import load_model

In [47]:
newmodel = load_model('keras_basics.h5')

In [50]:
newmodel.predict(scaled_X_test)[:10]

15/15 [==============================] - 0s 1ms/step


array([[0.02063654],
       [0.59386384],
       [0.27674893],
       [0.0169026 ],
       [0.04283488],
       [0.00433963],
       [0.10032575],
       [0.0053026 ],
       [0.01199585],
       [0.04205604]], dtype=float32)